services:
  tests:
    image: test_pw:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    environment:
      PROJECT: ${PROJECT:-all}
      WORKERS: ${WORKERS:-4}
      TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}
      TELEGRAM_BOT_ACCESS_TOKEN: ${TELEGRAM_BOT_ACCESS_TOKEN}
    command: ['sh', '-c', 'npx playwright test --project=$$PROJECT --workers=$$WORKERS']
    tty: true

  report:
    image: test_pw:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: sh -c "ls -la && allure generate allure-results --clean o allure-report"
    working_dir: /usr/workspace
