services:
  tests:
    image: test_pw:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - /usr/workspace/node_modules
    environment:
      PROJECT: ${PROJECT:-all}
      WORKERS: ${WORKERS:-4}
      TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}
      TELEGRAM_BOT_ACCESS_TOKEN: ${TELEGRAM_BOT_ACCESS_TOKEN}
      DEPLOYMENT_STATUS: ${DEPLOYMENT_STATUS:-}
      REPORT_URL: ${REPORT_URL:-}
      REPORT_ENV: ${REPORT_ENV:-}
      GITHUB_ACTOR: ${GITHUB_ACTOR:-}
      WORKFLOW_URL: ${WORKFLOW_URL:-}
    command: ['sh', '-c', 'npx playwright test --project=$$PROJECT --workers=$$WORKERS']
    tty: true

  report:
    image: test_pw:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
      - /usr/workspace/node_modules
    command: sh -c "ls -la && allure generate allure-results --clean -o allure-report"
    working_dir: /usr/workspace
